# Generated by knixl 0.3.1 from hosts/db.kdl
# Source: blake3:1b90… — do NOT edit.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{ config, lib, pkgs, ... }:
{
  services.restic.backups.db = lib.mkIf config.services.postgresql.enable {
    repository = "s3:https://s3.example.com/backups/db";
    initialize = true;
    timerConfig.OnCalendar = "daily";
    pruneOpts = [
      "--keep-daily 7"
      "--keep-weekly 4"
    ];
  };
}
