# Generated by knixl 0.3.1 from hosts/db.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  services.restic.backups.db = lib.mkIf (config.services.postgresql.enable) {
    initialize = true;
    pruneOpts = [
      "--keep-daily 7"
      "--keep-weekly 4"
    ];
    repository = "s3:https://s3.example.com/backups/db";
    timerConfig = {
      OnCalendar = "daily";
    };
  };
}
