# Generated by knixl 0.3.1 from hosts/db.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    ./db-backup.nix
  ];

  nixpkgs.hostPlatform = "x86_64-linux";
  services.postgresql.enable = true;
  services.postgresql.package = pkgs.postgresql_16;
  services.postgresql.ensureDatabases = [
    "app"
    "metrics"
  ];
  # listen-tcp #true overrides the base preset (enableTCPIP = false)
  services.postgresql.enableTCPIP = (lib.mkForce true);
}
