# Generated by knixl 0.3.1 from hosts/gateway.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  services.tailscale.enable = true;
  services.tailscale.extraUpFlags = [
    "--ssh"
  ];
  services.tailscale.authKeyFile = config.sops.secrets."tailscale-authkey".path;
}
