# Generated by knixl 0.3.1 from hosts/nas.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  networking.hostName = "nas";
  system.stateVersion = "25.11";
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.kernelPackages = pkgs.linuxPackages_6_18;
  boot.kernel.sysctl = {
    "net.bridge.bridge-nf-call-iptables" = 1;
    "net.ipv4.ip_forward" = 1;
    "vm.swappiness" = 10;
  };
  boot.kernelModules = [
    "br_netfilter"
  ];
  systemd.tmpfiles.rules = [
    "d /var/lib/bench 0755 wes users - -"
    "d /tmp/scratch 1777 - - 10d -"
  ];
  time.timeZone = "Europe/London";
  i18n.defaultLocale = "en_GB.UTF-8";
  users.mutableUsers = false;
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];
  nix.settings.trusted-users = [
    "wes"
  ];
  nix.settings.max-jobs = 4;
  environment.systemPackages = [
    pkgs.vim
    pkgs.git
  ];
  environment.sessionVariables = {
    KDIR = "/var/lib/bench/kdir";
  };
  programs.nix-ld.enable = true;
  programs.nix-ld.libraries = [
    pkgs.stdenv.cc.cc.lib
    pkgs.zlib
    pkgs.zstd
    pkgs.elfutils
  ];
  networking.hostId = "8425e349";
  boot.supportedFilesystems.zfs = true;
  boot.zfs.extraPools = [
    "tank"
  ];
  services.zfs.autoScrub.enable = true;
  boot.extraModprobeConfig = "options zfs zfs_arc_max=8589934592";
  boot.zfs.forceImportRoot = false;
  users.users."wes".isNormalUser = true;
  users.users."wes".extraGroups = [
    "wheel"
  ];
  users.users."wes".openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAExampleKeyForGoldenTest wes@nas"
  ];
  users.users."wes".description = "Wes Mason";
  users.users."wes".hashedPassword =
    "$6$rounds=100000$exampleSaltForGoldenTest$exampleHashDigestValueForTheGoldenTestOnly0123456789abcdefghij.";
  services.openssh.enable = true;
  services.openssh.settings.PasswordAuthentication = false;
  services.openssh.settings.KbdInteractiveAuthentication = false;
  services.openssh.ports = [
    22
    2222
  ];
  services.openssh.settings.PermitRootLogin = "prohibit-password";
}
