# Generated by knixl 0.3.1 from hosts/nas.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  networking.hostId = "8425e349";
  boot.supportedFilesystems.zfs = true;
  boot.zfs.extraPools = [
    "tank"
  ];
  services.zfs.autoScrub.enable = true;
  boot.extraModprobeConfig = "options zfs zfs_arc_max=8589934592";
  users.users."wes".isNormalUser = true;
  users.users."wes".extraGroups = [
    "wheel"
  ];
  users.users."wes".openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAExampleKeyForGoldenTest wes@nas"
  ];
  users.users."wes".description = "Wes Mason";
  services.openssh.enable = true;
  services.openssh.settings.PasswordAuthentication = false;
  services.openssh.settings.KbdInteractiveAuthentication = false;
  services.openssh.ports = [
    22
    2222
  ];
  services.openssh.settings.PermitRootLogin = "prohibit-password";
}
