# Generated by knixl 0.3.1 from hosts/pinned.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  environment.systemPackages = [
    (import
      (builtins.fetchGit ({
        rev = "0000000000000000000000000000000000000abc";
        shallow = true;
        url = "https://github.com/NixOS/nixpkgs";
      }))
      ({
        system = pkgs.system;
      })
    ).htop
    pkgs.ripgrep
  ];
}
