# Generated by knixl 0.3.1 from hosts/shared.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  _knixl0 = ''
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
  '';
in
{
  nixpkgs.hostPlatform = "x86_64-linux";
  services.nginx.virtualHosts."a.example.com".extraConfig = _knixl0;
  services.nginx.virtualHosts."b.example.com".extraConfig = _knixl0;
}
