# Generated by knixl 0.3.1 from hosts/vault.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  disko.devices.disk."main" = {
    content = {
      partitions = {
        "ESP" = {
          content = {
            format = "vfat";
            mountpoint = "/boot";
            type = "filesystem";
          };
          size = "512M";
          type = "EF00";
        };
        "crypt" = {
          content = {
            content = {
              format = "ext4";
              mountpoint = "/";
              type = "filesystem";
            };
            name = "cryptroot";
            type = "luks";
          };
          size = "100G";
        };
        "data" = {
          content = {
            pool = "tank";
            type = "zfs";
          };
          size = "100%";
        };
        "swap" = {
          content = {
            type = "swap";
          };
          size = "8G";
        };
      };
      type = "gpt";
    };
    device = "/dev/nvme0n1";
    type = "disk";
  };
  disko.devices.zpool."tank" = {
    datasets = {
      "media" = {
        mountpoint = "/tank/media";
        type = "zfs_fs";
      };
    };
    mountpoint = "/tank";
    type = "zpool";
  };
}
