# Generated by knixl 0.3.1 from hosts/vmhost.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  virtualisation.incus.enable = true;
  virtualisation.incus.ui.enable = true;
  virtualisation.incus.preseed.storage_pools = [
    {
      config = {
        source = "rpool/incus";
      };
      driver = "zfs";
      name = "default";
    }
  ];
  virtualisation.incus.preseed.networks = [
    {
      config = {
        "ipv4.address" = "auto";
        "ipv4.nat" = "true";
        "ipv6.address" = "fd42::1/64";
        "ipv6.nat" = "true";
      };
      name = "incusbr0";
      type = "bridge";
    }
  ];
  virtualisation.incus.preseed.profiles = [
    {
      devices = {
        eth0 = {
          name = "eth0";
          network = "incusbr0";
          type = "nic";
        };
        root = {
          path = "/";
          pool = "default";
          type = "disk";
        };
      };
      name = "default";
    }
  ];
  systemd.services."incus-https-address" = {
    after = [
      "incus.service"
      "network-online.target"
    ];
    description = "Bind the Incus HTTPS API to the tailscale0 address";
    path = [
      pkgs.iproute2
      pkgs.gawk
      pkgs.coreutils
      pkgs.incus
    ];
    requires = [
      "incus.service"
    ];
    script = ''
      addr=$(ip -4 -o addr show dev tailscale0 scope global | awk '{print $4}' | cut -d/ -f1 | head -n1)
      if [ -n "$addr" ]; then
        incus config set core.https_address "$addr:8443"
      fi
    '';
    serviceConfig = {
      Type = "oneshot";
    };
    wantedBy = [
      "multi-user.target"
    ];
    wants = [
      "network-online.target"
    ];
  };
  networking.firewall.trustedInterfaces = [
    "incusbr0"
  ];
  networking.firewall.interfaces."tailscale0".allowedTCPPorts = [
    8443
  ];
}
