# Generated by knixl 0.3.1 from hosts/vmhost.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  virtualisation.incus.enable = true;
  virtualisation.incus.ui.enable = true;
  virtualisation.incus.preseed.storage_pools = [
    {
      config = {
        source = "rpool/incus";
      };
      driver = "zfs";
      name = "default";
    }
  ];
  virtualisation.incus.preseed.networks = [
    {
      config = {
        "ipv4.address" = "auto";
        "ipv4.nat" = "true";
      };
      name = "incusbr0";
      type = "bridge";
    }
  ];
  virtualisation.incus.preseed.profiles = [
    {
      devices = {
        eth0 = {
          name = "eth0";
          network = "incusbr0";
          type = "nic";
        };
        root = {
          path = "/";
          pool = "default";
          type = "disk";
        };
      };
      name = "default";
    }
  ];
}
