# Generated by knixl 0.3.1 from hosts/web.kdl
# Source: blake3:9f2c… — do NOT edit.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{ config, lib, pkgs, ... }:
{
  nixpkgs.hostPlatform = "x86_64-linux";

  services.nginx.enable = true;
  services.nginx.recommendedTlsSettings = true;
  services.nginx.recommendedProxySettings = true;
  services.nginx.recommendedOptimisation = true;

  services.nginx.virtualHosts."example.com" = {
    forceSSL = true;
    enableACME = true;
    locations."/" = {
      proxyPass = "http://127.0.0.1:3000";
      extraConfig = ''
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
      '';
    };
  };

  security.acme.acceptTerms = true;
  security.acme.certs."example.com".email = "ops@example.com";

  # raw-nix passthrough (hosts/web.kdl:11)
  systemd.services.nginx.serviceConfig.MemoryMax = "512M";
}
