# Generated by knixl 0.3.1 from hosts/workstation.kdl
# Do NOT edit. Regenerate from the KDL source.
# Overrides: add a sibling module and use lib.mkForce / lib.mkAfter.
{
  config,
  lib,
  pkgs,
  ...
}:
{
  nixpkgs.hostPlatform = "x86_64-linux";
  home-manager.useUserPackages = true;
  home-manager.useGlobalPkgs = true;
  home-manager.users."wes".home.stateVersion = "24.11";
  home-manager.users."wes".home.sessionVariables."EDITOR" = "nvim";
  home-manager.users."wes".home.sessionVariables."PAGER" = "less";
  home-manager.users."wes".programs."git".enable = true;
  home-manager.users."wes".programs."fish".enable = true;
}
