//! End-to-end tests driving the real `knixl` binary against a temp project. An identity
//! formatter (`cat`, via KNIXL_FORMATTER) stands in for nixfmt so these run without it.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn examples() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples")
}

fn temp_project(tag: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!("knixl-cli-{}-{tag}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(root.join("hosts")).unwrap();
    fs::create_dir_all(root.join("modules/web-service")).unwrap();
    let ex = examples();
    for host in ["web.kdl", "db.kdl"] {
        fs::copy(ex.join("hosts").join(host), root.join("hosts").join(host)).unwrap();
    }
    // No lockfile: a fresh project, so the baseline versions match the running tool
    // (the copied examples lock pins nixfmt 1.3.1, which would skew against `cat`).
    fs::copy(
        ex.join("../modules/web-service/knixl-module.kdl"),
        root.join("modules/web-service/knixl-module.kdl"),
    )
    .unwrap();
    root
}

fn knixl(root: &Path, args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(args)
        .current_dir(root)
        .env("KNIXL_FORMATTER", "cat")
        .output()
        .expect("run knixl")
}

#[test]
fn doc_prints_a_typed_reference() {
    let root = temp_project("doc");
    let out = knixl(&root, &["doc", "host"]);
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(out.status.success());
    assert!(stdout.contains("host:"), "got: {stdout}");
    assert!(stdout.contains("system : string (required)"), "got: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn check_exits_regen_pending_when_nothing_is_generated() {
    let root = temp_project("check");
    let out = knixl(&root, &["check"]);
    // docs/05: Stale/Missing/Orphaned => exit 6 (RegenPending).
    assert_eq!(out.status.code(), Some(6), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("missing"), "got: {stdout}");
    assert!(stdout.contains("generated/hosts/web.nix"), "got: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn plan_defaults_to_exit_zero() {
    let root = temp_project("plan");
    let out = knixl(&root, &["plan"]);
    assert_eq!(out.status.code(), Some(0));
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn drift_is_detected_and_refused_without_accept_drift() {
    let root = temp_project("drift");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // Hand-edit a generated file: disk now diverges from the lock (tainted).
    let web = root.join("generated/hosts/web.nix");
    let edited = format!("{}\n# hand edit\n", fs::read_to_string(&web).unwrap());
    fs::write(&web, edited).unwrap();

    // check => Drift (exit 3).
    assert_eq!(knixl(&root, &["check"]).status.code(), Some(3));

    // generate refuses to clobber the edit (exit 3), leaving it in place.
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(3));
    assert!(fs::read_to_string(&web).unwrap().contains("# hand edit"));

    // --accept-drift knowingly overwrites (exit 0), discarding the edit.
    assert_eq!(knixl(&root, &["generate", "--accept-drift"]).status.code(), Some(0));
    assert!(!fs::read_to_string(&web).unwrap().contains("# hand edit"));

    let _ = fs::remove_dir_all(&root);
}

#[test]
fn prune_deletes_orphaned_files() {
    let root = temp_project("prune");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // An orphan: a knixl-headed file no host produces anymore.
    let orphan = root.join("generated/hosts/old.nix");
    fs::write(&orphan, "# Generated by knixl 0.3.1 from hosts/old.kdl\n{ }\n").unwrap();

    assert_eq!(knixl(&root, &["check"]).status.code(), Some(6), "orphan => RegenPending");
    assert_eq!(knixl(&root, &["generate", "--prune"]).status.code(), Some(0));
    assert!(!orphan.exists(), "--prune removed the orphan");

    let _ = fs::remove_dir_all(&root);
}

#[test]
fn upgrade_prints_migration_notes_for_a_module_bump() {
    let root = temp_project("upgrade");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // Record an older web-service in the lock: the manifest is 1.2.0, so this is version skew.
    let lock_path = root.join("knixl.lock.kdl");
    let lock = fs::read_to_string(&lock_path)
        .unwrap()
        .replace("module \"web-service\" version=\"1.2.0\"", "module \"web-service\" version=\"1.0.0\"");
    fs::write(&lock_path, lock).unwrap();
    // Make one output Missing so the skew forces the ack path (upgrade, not "up to date").
    fs::remove_file(root.join("generated/hosts/web.nix")).unwrap();

    let out = knixl(&root, &["upgrade"]);
    // No --yes: skew needs a human, exit 4 (NeedsAck).
    assert_eq!(out.status.code(), Some(4), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("web-service 1.0.0 -> 1.2.0"), "notes header: {stdout}");
    assert!(stdout.contains("enableACME"), "1.1.0 note shown: {stdout}");
    assert!(stdout.contains("serverAliases"), "1.2.0 note shown: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

/// A shim mimicking `nix-instantiate`: `--eval` prints a verdict, `--parse` exits 0.
fn nix_shim(tag: &str, exists: bool) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-nixshim-{}-{tag}", std::process::id()));
    let verdict = if exists { "true" } else { "false" };
    let script = format!(
        "#!/bin/sh\ncase \"$1\" in\n  --eval) echo \"{verdict}\" ;;\n  --parse) exit 0 ;;\nesac\n"
    );
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    f.flush().unwrap();
    drop(f); // close before exec, or spawning races with ETXTBSY
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

/// A shim mimicking `nix-build`: exits 0 when `build_ok`, else 1.
fn build_shim(tag: &str, build_ok: bool) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-buildshim-{}-{tag}", std::process::id()));
    let exit = if build_ok { 0 } else { 1 };
    let script = format!("#!/bin/sh\nexit {exit}\n");
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    f.flush().unwrap();
    drop(f); // close before exec, or spawning races with ETXTBSY
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[test]
fn install_build_refuses_when_the_build_fails() {
    let root = temp_project("install-build-fail");
    let eval_shim = nix_shim("build-fail-eval", true); // package resolves + parses
    let bad_build = build_shim("build-fail", false); // build exits non-zero
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "ripgrep", "--host", "web", "--yes", "--build"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &eval_shim)
        .env("KNIXL_NIX_BUILD", &bad_build)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "build failure exits Validation (5): {out:?}");
    // The KDL is untouched (reverted / never written): the build gate runs before commit.
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(!kdl.contains("ripgrep"), "no draft left behind: {kdl}");
    let _ = fs::remove_file(&eval_shim);
    let _ = fs::remove_file(&bad_build);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_drafts_verifies_and_regenerates() {
    let root = temp_project("install");
    let shim = nix_shim("ok", true);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "ripgrep", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &shim)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    // The KDL gained the package, format otherwise intact.
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(kdl.contains("package \"ripgrep\""), "kdl edited: {kdl}");
    assert!(kdl.contains("web-service \"example.com\""), "existing content kept: {kdl}");

    // The generated file has the package in systemPackages.
    let nix = fs::read_to_string(root.join("generated/hosts/web.nix")).unwrap();
    assert!(nix.contains("environment.systemPackages"), "systemPackages emitted: {nix}");
    assert!(nix.contains("pkgs.ripgrep"), "package reference emitted: {nix}");

    // And the project reconciles clean.
    let check = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["check"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .output()
        .expect("run check");
    assert_eq!(check.status.code(), Some(0), "check after install: {}", String::from_utf8_lossy(&check.stdout));
    let _ = fs::remove_file(&shim);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_refuses_a_nonexistent_package() {
    let root = temp_project("install-bad");
    let shim = nix_shim("bad", false); // package does not resolve
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "nnoopkg", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &shim)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "validation exit");
    // The KDL is untouched (reverted / never written).
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(!kdl.contains("nnoopkg"), "no draft left behind: {kdl}");
    let _ = fs::remove_file(&shim);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_strict_errors_when_nix_absent() {
    let root = temp_project("install-strict");
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "ripgrep", "--host", "web", "--yes", "--strict"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", "/nonexistent/knixl-no-nix")
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "strict + no nix => validation exit");
    let _ = fs::remove_dir_all(&root);
}

/// A shim mimicking `knixl-pin-resolve`: prints `stdout_line` and exits `code`.
fn resolver_shim(tag: &str, stdout_line: &str, stderr_line: &str, code: i32) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-resolvershim-{}-{tag}", std::process::id()));
    let script = format!(
        "#!/bin/sh\n[ -n \"{o}\" ] && echo \"{o}\"\n[ -n \"{e}\" ] && echo \"{e}\" 1>&2\nexit {code}\n",
        o = stdout_line, e = stderr_line,
    );
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    f.flush().unwrap();
    drop(f); // close before exec, or spawning races with ETXTBSY
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[test]
fn install_pkg_at_version_refuses_when_resolver_cannot_find_it() {
    let root = temp_project("install-version-nf");
    let ok_eval = nix_shim("version-nf-eval", true); // package resolves + parses
    let nf_resolver = resolver_shim("nf", "", "not found", 1);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@9.9.9", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &ok_eval)
        .env("KNIXL_PIN_RESOLVER", &nf_resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "unresolvable version refuses (Validation): {out:?}");
    // The KDL is untouched (reverted / never written): the pin gate runs before commit.
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(!kdl.contains("htop"), "no draft left behind: {kdl}");
    let _ = fs::remove_file(&ok_eval);
    let _ = fs::remove_file(&nf_resolver);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_pkg_at_version_resolves_writes_the_pin_and_regenerates() {
    let root = temp_project("install-version-ok");
    let ok_eval = nix_shim("version-ok-eval", true); // package resolves + parses
    let resolver = resolver_shim("ok", "abc123", "", 0);
    // A resolved rev differs from the (empty, fresh-project) baseline, so pin-strategy
    // selection would otherwise build-test for real: shim the build oracle to say yes,
    // deterministically choosing override (tried first) without touching the network.
    let ok_build = build_shim("version-ok-build", true);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@3.2.1", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &ok_eval)
        .env("KNIXL_NIX_BUILD", &ok_build)
        .env("KNIXL_PIN_RESOLVER", &resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(kdl.contains("package \"htop\" version=\"3.2.1\""), "kdl edited: {kdl}");

    let lock = fs::read_to_string(root.join("knixl.lock.kdl")).unwrap();
    assert!(lock.contains("pin \"htop\" version=\"3.2.1\""), "pin recorded: {lock}");
    assert!(lock.contains("nixpkgs-rev=\"abc123\""), "rev recorded: {lock}");

    let nix = fs::read_to_string(root.join("generated/hosts/web.nix")).unwrap();
    assert!(nix.contains("fetchGit"), "pinned import uses fetchGit: {nix}");
    assert!(nix.contains("abc123"), "pinned import carries the commit: {nix}");

    let _ = fs::remove_file(&ok_eval);
    let _ = fs::remove_file(&resolver);
    let _ = fs::remove_file(&ok_build);
    let _ = fs::remove_dir_all(&root);
}

/// A shim mimicking `nix-instantiate`: `--eval` says the package exists, but `--parse` fails.
/// Used to reach `commit_install`'s revert path *after* `write_pin` has already run (the pin
/// gate itself passed; the KDL failed to parse once drafted), to check the pin does not
/// linger.
fn nix_shim_parse_fails(tag: &str) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-nixshim-parsefail-{}-{tag}", std::process::id()));
    let script = "#!/bin/sh\ncase \"$1\" in\n  --eval) echo \"true\" ;;\n  --parse) exit 1 ;;\nesac\n";
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    f.flush().unwrap();
    drop(f); // close before exec, or spawning races with ETXTBSY
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[test]
fn install_pkg_at_version_reverts_the_pin_when_commit_fails_after_write_pin() {
    let root = temp_project("install-version-revert");
    let parse_fail_eval = nix_shim_parse_fails("revert");
    let resolver = resolver_shim("revert-ok", "abc123", "", 0);
    // As above: shim the build oracle so strategy selection deterministically picks
    // override (tried first) without a real (network-dependent) build test.
    let ok_build = build_shim("version-revert-build", true);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@3.2.1", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &parse_fail_eval)
        .env("KNIXL_NIX_BUILD", &ok_build)
        .env("KNIXL_PIN_RESOLVER", &resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "parse failure after the pin gate: {out:?}");

    // The KDL is reverted (no dangling `version` prop)...
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(!kdl.contains("htop"), "kdl reverted: {kdl}");

    // ...and the pin `write_pin` recorded before the parse check must not be left dangling.
    let lock_path = root.join("knixl.lock.kdl");
    if lock_path.exists() {
        let lock = fs::read_to_string(&lock_path).unwrap();
        assert!(!lock.contains("pin \"htop\""), "pin not left dangling after revert: {lock}");
    }

    let _ = fs::remove_file(&parse_fail_eval);
    let _ = fs::remove_file(&resolver);
    let _ = fs::remove_file(&ok_build);
    let _ = fs::remove_dir_all(&root);
}

/// A shim mimicking `nix-build` for pin-strategy selection: passes the override candidate,
/// fails the commit-mix candidate. The two expressions are distinguished by `overrideAttrs`,
/// which only `override_test_expr` emits.
fn strategy_build_shim(tag: &str) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-strategybuildshim-{}-{tag}", std::process::id()));
    let script = "#!/bin/sh\ncase \"$*\" in\n  *overrideAttrs*) exit 0 ;;\n  *) exit 1 ;;\nesac\n";
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    f.flush().unwrap();
    drop(f); // close before exec, or spawning races with ETXTBSY
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[test]
fn install_pkg_at_version_prefers_override_when_it_builds() {
    let root = temp_project("install-strategy-override");
    let ok_eval = nix_shim("strategy-override-eval", true); // package resolves + parses
    let resolver = resolver_shim("strategy-override", "abc123", "", 0);
    let build = strategy_build_shim("override");
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@3.2.1", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &ok_eval)
        .env("KNIXL_NIX_BUILD", &build)
        .env("KNIXL_PIN_RESOLVER", &resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let lock = fs::read_to_string(root.join("knixl.lock.kdl")).unwrap();
    assert!(lock.contains("strategy=\"override\""), "override strategy recorded: {lock}");

    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("via override"), "status line names the strategy: {stdout}");

    let _ = fs::remove_file(&ok_eval);
    let _ = fs::remove_file(&resolver);
    let _ = fs::remove_file(&build);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_pkg_at_version_no_abi_check_skips_the_build_shim() {
    let root = temp_project("install-no-abi-check");
    let ok_eval = nix_shim("no-abi-check-eval", true); // package resolves + parses
    let resolver = resolver_shim("no-abi-check", "abc123", "", 0);
    // A build shim that always fails: if --no-abi-check really skips the check, it is never
    // invoked, and the install still succeeds with commit-mix (the run would exit 5 with
    // both candidates failing if the shim were called).
    let never_build = build_shim("no-abi-check-build", false);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@3.2.1", "--host", "web", "--yes", "--no-abi-check"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &ok_eval)
        .env("KNIXL_NIX_BUILD", &never_build)
        .env("KNIXL_PIN_RESOLVER", &resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let lock = fs::read_to_string(root.join("knixl.lock.kdl")).unwrap();
    assert!(lock.contains("pin \"htop\""), "pin recorded: {lock}");
    assert!(!lock.contains("strategy=\"override\""), "commit-mix recorded (no strategy attr): {lock}");

    let _ = fs::remove_file(&ok_eval);
    let _ = fs::remove_file(&resolver);
    let _ = fs::remove_file(&never_build);
    let _ = fs::remove_dir_all(&root);
}

/// Declares a `nixpkgs release="25.05"` baseline on the copied `web` host, in place.
fn declare_baseline_release(root: &Path, release: &str) {
    let path = root.join("hosts/web.kdl");
    let src = fs::read_to_string(&path).unwrap();
    let edited = src.replacen(
        "system \"x86_64-linux\"",
        &format!("system \"x86_64-linux\"\n    nixpkgs release=\"{release}\""),
        1,
    );
    assert_ne!(src, edited, "system line not found to anchor the nixpkgs node");
    fs::write(&path, edited).unwrap();
}

#[test]
fn install_with_a_declared_release_resolves_and_writes_the_baseline() {
    let root = temp_project("install-baseline");
    declare_baseline_release(&root, "25.05");

    let ok_eval = nix_shim("baseline-eval", true); // package resolves + parses
    let pin_resolver = resolver_shim("baseline-pin", "abc123", "", 0);
    let baseline_resolver = resolver_shim("baseline-rev", "deadbeef", "", 0);
    // Distinct pin/baseline revs would otherwise build-test for real; shim it to succeed.
    let ok_build = build_shim("baseline-build", true);

    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "htop@3.2.1", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &ok_eval)
        .env("KNIXL_NIX_BUILD", &ok_build)
        .env("KNIXL_PIN_RESOLVER", &pin_resolver)
        .env("KNIXL_BASELINE_RESOLVER", &baseline_resolver)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("25.05") && stdout.contains("deadbeef"), "status line: {stdout}");

    let lock = fs::read_to_string(root.join("knixl.lock.kdl")).unwrap();
    assert!(lock.contains("baseline release=\"25.05\""), "baseline recorded: {lock}");
    assert!(lock.contains("nixpkgs-rev=\"deadbeef\""), "resolved rev recorded: {lock}");

    let _ = fs::remove_file(&ok_eval);
    let _ = fs::remove_file(&pin_resolver);
    let _ = fs::remove_file(&baseline_resolver);
    let _ = fs::remove_file(&ok_build);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn check_reports_a_validation_error_for_an_unresolved_declared_release() {
    let root = temp_project("check-baseline-unresolved");
    declare_baseline_release(&root, "25.05");

    let out = knixl(&root, &["check"]);
    assert_eq!(out.status.code(), Some(5), "stdout: {}", String::from_utf8_lossy(&out.stdout));
    let stderr = String::from_utf8_lossy(&out.stderr);
    assert!(stderr.contains("web") && stderr.contains("25.05") && stderr.contains("knixl upgrade"), "stderr: {stderr}");

    let _ = fs::remove_dir_all(&root);
}

#[test]
fn generate_writes_files_then_check_is_clean() {
    let root = temp_project("gen");

    let gen = knixl(&root, &["generate"]);
    assert_eq!(gen.status.code(), Some(0), "generate: {}", String::from_utf8_lossy(&gen.stderr));

    for f in ["web.nix", "db.nix", "db-backup.nix"] {
        assert!(root.join("generated/hosts").join(f).exists(), "{f} was written");
    }

    // After a clean apply the lock matches disk, so check is Clean (exit 0).
    let check = knixl(&root, &["check"]);
    assert_eq!(
        check.status.code(),
        Some(0),
        "check after generate: {}",
        String::from_utf8_lossy(&check.stdout)
    );
    let _ = fs::remove_dir_all(&root);
}
