//! End-to-end tests driving the real `knixl` binary against a temp project. An identity
//! formatter (`cat`, via KNIXL_FORMATTER) stands in for nixfmt so these run without it.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn examples() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples")
}

fn temp_project(tag: &str) -> PathBuf {
    let root = std::env::temp_dir().join(format!("knixl-cli-{}-{tag}", std::process::id()));
    let _ = fs::remove_dir_all(&root);
    fs::create_dir_all(root.join("hosts")).unwrap();
    fs::create_dir_all(root.join("modules/web-service")).unwrap();
    let ex = examples();
    for host in ["web.kdl", "db.kdl"] {
        fs::copy(ex.join("hosts").join(host), root.join("hosts").join(host)).unwrap();
    }
    // No lockfile: a fresh project, so the baseline versions match the running tool
    // (the copied examples lock pins nixfmt 1.3.1, which would skew against `cat`).
    fs::copy(
        ex.join("../modules/web-service/knixl-module.kdl"),
        root.join("modules/web-service/knixl-module.kdl"),
    )
    .unwrap();
    root
}

fn knixl(root: &Path, args: &[&str]) -> std::process::Output {
    Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(args)
        .current_dir(root)
        .env("KNIXL_FORMATTER", "cat")
        .output()
        .expect("run knixl")
}

#[test]
fn doc_prints_a_typed_reference() {
    let root = temp_project("doc");
    let out = knixl(&root, &["doc", "host"]);
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(out.status.success());
    assert!(stdout.contains("host:"), "got: {stdout}");
    assert!(stdout.contains("system : string (required)"), "got: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn check_exits_regen_pending_when_nothing_is_generated() {
    let root = temp_project("check");
    let out = knixl(&root, &["check"]);
    // docs/05: Stale/Missing/Orphaned => exit 6 (RegenPending).
    assert_eq!(out.status.code(), Some(6), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("missing"), "got: {stdout}");
    assert!(stdout.contains("generated/hosts/web.nix"), "got: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn plan_defaults_to_exit_zero() {
    let root = temp_project("plan");
    let out = knixl(&root, &["plan"]);
    assert_eq!(out.status.code(), Some(0));
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn drift_is_detected_and_refused_without_accept_drift() {
    let root = temp_project("drift");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // Hand-edit a generated file: disk now diverges from the lock (tainted).
    let web = root.join("generated/hosts/web.nix");
    let edited = format!("{}\n# hand edit\n", fs::read_to_string(&web).unwrap());
    fs::write(&web, edited).unwrap();

    // check => Drift (exit 3).
    assert_eq!(knixl(&root, &["check"]).status.code(), Some(3));

    // generate refuses to clobber the edit (exit 3), leaving it in place.
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(3));
    assert!(fs::read_to_string(&web).unwrap().contains("# hand edit"));

    // --accept-drift knowingly overwrites (exit 0), discarding the edit.
    assert_eq!(knixl(&root, &["generate", "--accept-drift"]).status.code(), Some(0));
    assert!(!fs::read_to_string(&web).unwrap().contains("# hand edit"));

    let _ = fs::remove_dir_all(&root);
}

#[test]
fn prune_deletes_orphaned_files() {
    let root = temp_project("prune");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // An orphan: a knixl-headed file no host produces anymore.
    let orphan = root.join("generated/hosts/old.nix");
    fs::write(&orphan, "# Generated by knixl 0.3.1 from hosts/old.kdl\n{ }\n").unwrap();

    assert_eq!(knixl(&root, &["check"]).status.code(), Some(6), "orphan => RegenPending");
    assert_eq!(knixl(&root, &["generate", "--prune"]).status.code(), Some(0));
    assert!(!orphan.exists(), "--prune removed the orphan");

    let _ = fs::remove_dir_all(&root);
}

#[test]
fn upgrade_prints_migration_notes_for_a_module_bump() {
    let root = temp_project("upgrade");
    assert_eq!(knixl(&root, &["generate"]).status.code(), Some(0));

    // Record an older web-service in the lock: the manifest is 1.2.0, so this is version skew.
    let lock_path = root.join("knixl.lock.kdl");
    let lock = fs::read_to_string(&lock_path)
        .unwrap()
        .replace("module \"web-service\" version=\"1.2.0\"", "module \"web-service\" version=\"1.0.0\"");
    fs::write(&lock_path, lock).unwrap();
    // Make one output Missing so the skew forces the ack path (upgrade, not "up to date").
    fs::remove_file(root.join("generated/hosts/web.nix")).unwrap();

    let out = knixl(&root, &["upgrade"]);
    // No --yes: skew needs a human, exit 4 (NeedsAck).
    assert_eq!(out.status.code(), Some(4), "stderr: {}", String::from_utf8_lossy(&out.stderr));
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(stdout.contains("web-service 1.0.0 -> 1.2.0"), "notes header: {stdout}");
    assert!(stdout.contains("enableACME"), "1.1.0 note shown: {stdout}");
    assert!(stdout.contains("serverAliases"), "1.2.0 note shown: {stdout}");
    let _ = fs::remove_dir_all(&root);
}

/// A shim mimicking `nix-instantiate`: `--eval` prints a verdict, `--parse` exits 0.
fn nix_shim(tag: &str, exists: bool) -> PathBuf {
    use std::io::Write;
    use std::os::unix::fs::PermissionsExt;
    let path = std::env::temp_dir().join(format!("knixl-cli-nixshim-{}-{tag}", std::process::id()));
    let verdict = if exists { "true" } else { "false" };
    let script = format!(
        "#!/bin/sh\ncase \"$1\" in\n  --eval) echo \"{verdict}\" ;;\n  --parse) exit 0 ;;\nesac\n"
    );
    let mut f = fs::File::create(&path).unwrap();
    f.write_all(script.as_bytes()).unwrap();
    fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();
    path
}

#[test]
fn install_drafts_verifies_and_regenerates() {
    let root = temp_project("install");
    let shim = nix_shim("ok", true);
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "ripgrep", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &shim)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(0), "stderr: {}", String::from_utf8_lossy(&out.stderr));

    // The KDL gained the package, format otherwise intact.
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(kdl.contains("package \"ripgrep\""), "kdl edited: {kdl}");
    assert!(kdl.contains("web-service \"example.com\""), "existing content kept: {kdl}");

    // The generated file has the package in systemPackages.
    let nix = fs::read_to_string(root.join("generated/hosts/web.nix")).unwrap();
    assert!(nix.contains("environment.systemPackages"), "systemPackages emitted: {nix}");
    assert!(nix.contains("pkgs.ripgrep"), "package reference emitted: {nix}");

    // And the project reconciles clean.
    let check = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["check"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .output()
        .expect("run check");
    assert_eq!(check.status.code(), Some(0), "check after install: {}", String::from_utf8_lossy(&check.stdout));
    let _ = fs::remove_file(&shim);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_refuses_a_nonexistent_package() {
    let root = temp_project("install-bad");
    let shim = nix_shim("bad", false); // package does not resolve
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "nnoopkg", "--host", "web", "--yes"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", &shim)
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "validation exit");
    // The KDL is untouched (reverted / never written).
    let kdl = fs::read_to_string(root.join("hosts/web.kdl")).unwrap();
    assert!(!kdl.contains("nnoopkg"), "no draft left behind: {kdl}");
    let _ = fs::remove_file(&shim);
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn install_strict_errors_when_nix_absent() {
    let root = temp_project("install-strict");
    let out = Command::new(env!("CARGO_BIN_EXE_knixl"))
        .args(["install", "ripgrep", "--host", "web", "--yes", "--strict"])
        .current_dir(&root)
        .env("KNIXL_FORMATTER", "cat")
        .env("KNIXL_NIX", "/nonexistent/knixl-no-nix")
        .output()
        .expect("run knixl install");
    assert_eq!(out.status.code(), Some(5), "strict + no nix => validation exit");
    let _ = fs::remove_dir_all(&root);
}

#[test]
fn generate_writes_files_then_check_is_clean() {
    let root = temp_project("gen");

    let gen = knixl(&root, &["generate"]);
    assert_eq!(gen.status.code(), Some(0), "generate: {}", String::from_utf8_lossy(&gen.stderr));

    for f in ["web.nix", "db.nix", "db-backup.nix"] {
        assert!(root.join("generated/hosts").join(f).exists(), "{f} was written");
    }

    // After a clean apply the lock matches disk, so check is Clean (exit 0).
    let check = knixl(&root, &["check"]);
    assert_eq!(
        check.status.code(),
        Some(0),
        "check after generate: {}",
        String::from_utf8_lossy(&check.stdout)
    );
    let _ = fs::remove_dir_all(&root);
}
