//! Emit the opt-in system-assembly flake (ADR 0009): nixosConfigurations.<host>, each host
//! built against its own baseline nixpkgs rev, pinned by fetchGit (a full rev is a pure pin).

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeHost {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
}

/// An installer target (ADR 0012): builds to an ISO. `system` is the platform double keying its
/// `packages.<system>` output; `baseline_rev` pins nixpkgs like a host.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeInstaller {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
    pub system: String,
}

/// A Nix identifier derived from an installer name for a `let` binding (names are simple in
/// practice, but hyphens and other non-ident chars are mapped to `_` defensively).
fn let_ident(name: &str) -> String {
    let mut out = String::from("installer_");
    for c in name.chars() {
        out.push(if c.is_ascii_alphanumeric() { c } else { '_' });
    }
    out
}

/// Escape a value spliced into a Nix double-quoted string literal: backslash, double-quote,
/// and the antiquotation opener `${`.
fn esc(v: &str) -> String {
    v.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${")
}

/// Render the system flake. Hosts are emitted in `name` order so the output is a pure function
/// of the input set (sorted here defensively, independent of caller order). The text is
/// unformatted Nix; the caller runs it through the pinned formatter before hashing.
///
/// Each host is built with `nixos/lib/eval-config.nix` from its baseline nixpkgs: that is the
/// self-contained system constructor. `lib.nixosSystem` is a flake-only lib extension and is
/// NOT present on a plain `import <nixpkgs> {}` set, so it cannot be used here. `fetchGit` with
/// a full rev is a pure pin; `shallow = true` matches the package-pin emit idiom.
pub fn render_system_flake(
    hosts: &[FlakeHost],
    installers: &[FlakeInstaller],
    state_version: &str,
    nixpkgs_url: &str,
) -> String {
    let mut sorted: Vec<&FlakeHost> = hosts.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut inst: Vec<&FlakeInstaller> = installers.iter().collect();
    inst.sort_by(|a, b| a.name.cmp(&b.name));

    let mut s = String::new();
    s.push_str("# Generated by knixl. Do NOT edit; regenerate with `knixl generate`.\n");
    s.push_str("{\n");
    s.push_str("  description = \"knixl-generated system\";\n");
    s.push_str("  outputs = { ... }:\n");
    s.push_str("    let\n");
    s.push_str(&format!(
        "      evalAt = rev: import \"${{builtins.fetchGit {{ url = \"{}\"; rev = rev; shallow = true; }}}}/nixos/lib/eval-config.nix\";\n",
        esc(nixpkgs_url)
    ));
    // One `let` binding per installer, so both nixosConfigurations and packages can name the
    // same evaluated configuration (ADR 0012).
    for i in &inst {
        s.push_str(&format!(
            "      {} = evalAt \"{}\" {{\n",
            let_ident(&i.name),
            esc(&i.baseline_rev)
        ));
        s.push_str("        modules = [\n");
        s.push_str(&format!("          {}\n", i.module_path));
        s.push_str(&format!(
            "          {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("        ];\n");
        s.push_str("      };\n");
    }
    s.push_str("    in\n");
    s.push_str("    {\n");
    s.push_str("      nixosConfigurations = {\n");
    for h in sorted {
        s.push_str(&format!(
            "        \"{}\" = evalAt \"{}\" {{\n",
            esc(&h.name),
            esc(&h.baseline_rev)
        ));
        s.push_str("          modules = [\n");
        s.push_str(&format!("            {}\n", h.module_path));
        s.push_str(&format!(
            "            {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("          ];\n");
        s.push_str("        };\n");
    }
    for i in &inst {
        s.push_str(&format!(
            "        \"{}\" = {};\n",
            esc(&i.name),
            let_ident(&i.name)
        ));
    }
    s.push_str("      };\n");
    // ISO build outputs, keyed by each installer's target system.
    if !inst.is_empty() {
        s.push_str("      packages = {\n");
        for i in &inst {
            s.push_str(&format!("        \"{}\" = {{\n", esc(&i.system)));
            s.push_str(&format!(
                "          \"{}-iso\" = {}.config.system.build.isoImage;\n",
                esc(&i.name),
                let_ident(&i.name)
            ));
            s.push_str("        };\n");
        }
        s.push_str("      };\n");
    }
    s.push_str("    };\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hosts() -> Vec<FlakeHost> {
        vec![
            FlakeHost {
                name: "web".into(),
                baseline_rev: "rev-web".into(),
                module_path: "./hosts/web.nix".into(),
            },
            FlakeHost {
                name: "db".into(),
                baseline_rev: "rev-db".into(),
                module_path: "./hosts/db.nix".into(),
            },
        ]
    }

    #[test]
    fn deterministic_and_name_ordered() {
        let a = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        let b = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        assert_eq!(a, b, "same input, byte-identical");
        // Order-independent: reversing the input yields the same text (sorted by name).
        let mut rev = hosts();
        rev.reverse();
        assert_eq!(
            render_system_flake(&rev, &[], "25.05", "https://github.com/NixOS/nixpkgs"),
            a
        );
        // db precedes web in the output.
        assert!(
            a.find("\"db\"").unwrap() < a.find("\"web\"").unwrap(),
            "name order: {a}"
        );
    }

    #[test]
    fn emits_per_host_pin_and_state_version() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://example.com/nixpkgs");
        assert!(out.contains("nixosConfigurations"));
        assert!(out.contains("\"web\""));
        assert!(out.contains("rev-web"));
        assert!(out.contains("rev-db"));
        assert!(out.contains("./hosts/web.nix"));
        assert!(out.contains("system.stateVersion = \"25.05\""));
        assert!(out.contains("https://example.com/nixpkgs"));
        assert!(out.contains("builtins.fetchGit"));
        assert!(!out.contains("inputs ="), "no flake inputs");
        // Regression guard: the flake must use eval-config.nix, never lib.nixosSystem (which
        // does not exist on a plain imported nixpkgs set and fails to evaluate).
        assert!(
            out.contains("eval-config.nix"),
            "uses the eval-config constructor: {out}"
        );
        assert!(
            !out.contains("nixosSystem"),
            "must not use lib.nixosSystem: {out}"
        );
    }

    #[test]
    fn escapes_quotes_in_interpolated_values() {
        let hs = vec![FlakeHost {
            name: "web".into(),
            baseline_rev: "rev".into(),
            module_path: "./hosts/web.nix".into(),
        }];
        // A url with a quote must not break out of its Nix string literal.
        let out = render_system_flake(&hs, &[], "25.05", "https://x/\"evil");
        assert!(out.contains("https://x/\\\"evil"), "quote escaped: {out}");
    }

    #[test]
    fn emits_installer_config_and_iso_package_output() {
        let installers = vec![FlakeInstaller {
            name: "usb".into(),
            baseline_rev: "rev-inst".into(),
            module_path: "./installer/usb.nix".into(),
            system: "x86_64-linux".into(),
        }];
        let out = render_system_flake(&hosts(), &installers, "25.05", "https://x/nixpkgs");
        // a let binding the config, referenced by both nixosConfigurations and packages
        assert!(out.contains("installer_usb = evalAt \"rev-inst\""));
        assert!(out.contains("./installer/usb.nix"));
        assert!(out.contains("\"usb\" = installer_usb;"));
        // the ISO package output, keyed by the installer's system
        assert!(out.contains("packages = {"));
        assert!(out.contains("\"x86_64-linux\" = {"));
        assert!(
            out.contains("\"usb-iso\" = installer_usb.config.system.build.isoImage;"),
            "iso output: {out}"
        );
    }

    #[test]
    fn no_installers_means_no_packages_output() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://x/nixpkgs");
        assert!(
            !out.contains("packages = {"),
            "no packages when no installers"
        );
    }
}
