//! Emit the opt-in system-assembly flake (ADR 0009): nixosConfigurations.<host>, each host
//! built against its own baseline nixpkgs rev, pinned by fetchGit (a full rev is a pure pin).

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeHost {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
    /// The host's declared `system` double, passed to `nixosSystem` in input mode.
    pub system: Option<String>,
    /// Input-mode module expressions listed ahead of the host module, e.g.
    /// `inputs."disko".nixosModules."disko"` (ADR 0014).
    pub input_modules: Vec<String>,
    /// Input-mode inline module expressions listed after the host module (the sops wiring).
    pub inline_modules: Vec<String>,
}

/// An image target (ADR 0012, 0013): an installer ISO or an lxc image. `system` is the platform
/// double keying its `packages.<system>` output; `baseline_rev` pins nixpkgs like a host; `kind`
/// selects the flake output shape.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeImage {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
    pub system: String,
    pub kind: crate::project::ImageKind,
}

impl FlakeImage {
    /// The `packages.<system>` outputs this image contributes, as `(output-name, expression)`
    /// where the expression reads a build product off the image's evaluated config (`binding`).
    fn outputs(&self, binding: &str) -> Vec<(String, String)> {
        match self.kind {
            crate::project::ImageKind::Installer => vec![(
                format!("{}-iso", self.name),
                format!("{binding}.config.system.build.isoImage"),
            )],
            // incus image import takes both a rootfs and a metadata tarball, so both are exposed.
            crate::project::ImageKind::GuestLxc => vec![
                (
                    format!("{}-lxc", self.name),
                    format!("{binding}.config.system.build.tarball"),
                ),
                (
                    format!("{}-lxc-metadata", self.name),
                    format!("{binding}.config.system.build.metadata"),
                ),
            ],
        }
    }
}

/// A Nix identifier derived from an image name for a `let` binding (names are simple in practice,
/// but hyphens and other non-ident chars are mapped to `_` defensively).
fn let_ident(name: &str) -> String {
    let mut out = String::from("image_");
    for c in name.chars() {
        out.push(if c.is_ascii_alphanumeric() { c } else { '_' });
    }
    out
}

/// Escape a value spliced into a Nix double-quoted string literal: backslash, double-quote,
/// and the antiquotation opener `${`.
fn esc(v: &str) -> String {
    v.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${")
}

/// Render the system flake. Hosts are emitted in `name` order so the output is a pure function
/// of the input set (sorted here defensively, independent of caller order). The text is
/// unformatted Nix; the caller runs it through the pinned formatter before hashing.
///
/// Each host is built with `nixos/lib/eval-config.nix` from its baseline nixpkgs: that is the
/// self-contained system constructor. `lib.nixosSystem` is a flake-only lib extension and is
/// NOT present on a plain `import <nixpkgs> {}` set, so it cannot be used here. `fetchGit` with
/// a full rev is a pure pin; `shallow = true` matches the package-pin emit idiom.
pub fn render_system_flake(
    hosts: &[FlakeHost],
    images: &[FlakeImage],
    state_version: &str,
    nixpkgs_url: &str,
) -> String {
    let mut sorted: Vec<&FlakeHost> = hosts.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut inst: Vec<&FlakeImage> = images.iter().collect();
    inst.sort_by(|a, b| a.name.cmp(&b.name));

    let mut s = String::new();
    s.push_str("# Generated by knixl. Do NOT edit; regenerate with `knixl generate`.\n");
    s.push_str("{\n");
    s.push_str("  description = \"knixl-generated system\";\n");
    s.push_str("  outputs = { ... }:\n");
    s.push_str("    let\n");
    s.push_str(&format!(
        "      evalAt = rev: import \"${{builtins.fetchGit {{ url = \"{}\"; rev = rev; shallow = true; }}}}/nixos/lib/eval-config.nix\";\n",
        esc(nixpkgs_url)
    ));
    // One `let` binding per image target, so both nixosConfigurations and packages can name the
    // same evaluated configuration (ADR 0012, 0013).
    for i in &inst {
        s.push_str(&format!(
            "      {} = evalAt \"{}\" {{\n",
            let_ident(&i.name),
            esc(&i.baseline_rev)
        ));
        s.push_str("        modules = [\n");
        s.push_str(&format!("          {}\n", i.module_path));
        s.push_str(&format!(
            "          {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("        ];\n");
        s.push_str("      };\n");
    }
    s.push_str("    in\n");
    s.push_str("    {\n");
    s.push_str("      nixosConfigurations = {\n");
    for h in sorted {
        s.push_str(&format!(
            "        \"{}\" = evalAt \"{}\" {{\n",
            esc(&h.name),
            esc(&h.baseline_rev)
        ));
        s.push_str("          modules = [\n");
        s.push_str(&format!("            {}\n", h.module_path));
        s.push_str(&format!(
            "            {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("          ];\n");
        s.push_str("        };\n");
    }
    for i in &inst {
        s.push_str(&format!(
            "        \"{}\" = {};\n",
            esc(&i.name),
            let_ident(&i.name)
        ));
    }
    s.push_str("      };\n");
    push_packages(&mut s, &inst);
    s.push_str("    };\n");
    s.push_str("}\n");
    s
}

/// Image build outputs, grouped by target system (so two images on the same system share one
/// `packages.<system>` set rather than emitting a duplicate key).
fn push_packages(s: &mut String, inst: &[&FlakeImage]) {
    if inst.is_empty() {
        return;
    }
    let mut by_system: std::collections::BTreeMap<&str, Vec<(String, String)>> =
        std::collections::BTreeMap::new();
    for i in inst {
        by_system
            .entry(i.system.as_str())
            .or_default()
            .extend(i.outputs(&let_ident(&i.name)));
    }
    s.push_str("      packages = {\n");
    for (system, mut outs) in by_system {
        outs.sort_by(|a, b| a.0.cmp(&b.0));
        s.push_str(&format!("        \"{}\" = {{\n", esc(system)));
        for (name, expr) in outs {
            s.push_str(&format!("          \"{}\" = {};\n", esc(&name), expr));
        }
        s.push_str("        };\n");
    }
    s.push_str("      };\n");
}

/// A flake input as the generated flake declares it (ADR 0014): `url` already carries the
/// pinned rev, `follows` is sorted by key.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeInputSpec {
    pub name: String,
    pub url: String,
    pub flake: bool,
    pub follows: Vec<(String, String)>,
}

/// Write `rev` into a flake ref so it locks to exactly that commit: the path form for
/// `github:` refs (`github:owner/repo/<rev>`), a `rev` query parameter otherwise.
pub fn pinned_url(url: &str, rev: &str) -> String {
    if url.starts_with("github:") {
        return match url.split_once('?') {
            Some((path, query)) => format!("{path}/{rev}?{query}"),
            None => format!("{url}/{rev}"),
        };
    }
    let sep = if url.contains('?') { '&' } else { '?' };
    format!("{url}{sep}rev={rev}")
}

/// Render the input-mode system flake (ADR 0014): declared inputs pinned by rev, every host
/// and image built with `nixpkgs.lib.nixosSystem` from the `nixpkgs` input. Hosts pass their
/// `system` when known, and installers pass theirs; guest images don't, since the lxc base
/// module sets the platform. Inputs, hosts and images are emitted in name order.
pub fn render_input_flake(
    inputs: &[FlakeInputSpec],
    hosts: &[FlakeHost],
    images: &[FlakeImage],
    state_version: &str,
    formatter: Option<&str>,
) -> String {
    let mut ins: Vec<&FlakeInputSpec> = inputs.iter().collect();
    ins.sort_by(|a, b| a.name.cmp(&b.name));
    let mut sorted: Vec<&FlakeHost> = hosts.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut inst: Vec<&FlakeImage> = images.iter().collect();
    inst.sort_by(|a, b| a.name.cmp(&b.name));

    let modules =
        |s: &mut String, indent: &str, before: &[String], path: &str, after: &[String]| {
            s.push_str(&format!("{indent}modules = [\n"));
            for m in before {
                s.push_str(&format!("{indent}  {m}\n"));
            }
            s.push_str(&format!("{indent}  {path}\n"));
            for m in after {
                s.push_str(&format!("{indent}  {m}\n"));
            }
            s.push_str(&format!(
                "{indent}  {{ system.stateVersion = \"{}\"; }}\n",
                esc(state_version)
            ));
            s.push_str(&format!("{indent}];\n"));
        };

    let mut s = String::new();
    s.push_str("# Generated by knixl. Do NOT edit; regenerate with `knixl generate`.\n");
    s.push_str("{\n");
    s.push_str("  description = \"knixl-generated system\";\n");
    s.push_str("  inputs = {\n");
    for i in &ins {
        s.push_str(&format!("    \"{}\" = {{\n", esc(&i.name)));
        s.push_str(&format!("      url = \"{}\";\n", esc(&i.url)));
        if !i.flake {
            s.push_str("      flake = false;\n");
        }
        for (key, target) in &i.follows {
            s.push_str(&format!(
                "      inputs.\"{}\".follows = \"{}\";\n",
                esc(key),
                esc(target)
            ));
        }
        s.push_str("    };\n");
    }
    s.push_str("  };\n");
    s.push_str("  outputs = { nixpkgs, ... }@inputs:\n");
    s.push_str("    let\n");
    for i in &inst {
        s.push_str(&format!(
            "      {} = nixpkgs.lib.nixosSystem {{\n",
            let_ident(&i.name)
        ));
        if i.kind == crate::project::ImageKind::Installer {
            s.push_str(&format!("        system = \"{}\";\n", esc(&i.system)));
        }
        modules(&mut s, "        ", &[], &i.module_path, &[]);
        s.push_str("      };\n");
    }
    s.push_str("    in\n");
    s.push_str("    {\n");
    s.push_str("      nixosConfigurations = {\n");
    for h in &sorted {
        s.push_str(&format!(
            "        \"{}\" = nixpkgs.lib.nixosSystem {{\n",
            esc(&h.name)
        ));
        if let Some(system) = &h.system {
            s.push_str(&format!("          system = \"{}\";\n", esc(system)));
        }
        modules(
            &mut s,
            "          ",
            &h.input_modules,
            &h.module_path,
            &h.inline_modules,
        );
        s.push_str("        };\n");
    }
    for i in &inst {
        s.push_str(&format!(
            "        \"{}\" = {};\n",
            esc(&i.name),
            let_ident(&i.name)
        ));
    }
    s.push_str("      };\n");
    push_packages(&mut s, &inst);
    if let Some(attr) = formatter {
        let systems: std::collections::BTreeSet<&str> =
            sorted.iter().filter_map(|h| h.system.as_deref()).collect();
        if !systems.is_empty() {
            s.push_str("      formatter = {\n");
            for system in systems {
                s.push_str(&format!(
                    "        \"{0}\" = nixpkgs.legacyPackages.\"{0}\".\"{1}\";\n",
                    esc(system),
                    esc(attr)
                ));
            }
            s.push_str("      };\n");
        }
    }
    s.push_str("    };\n");
    s.push_str("}\n");
    s
}

/// Compare a nix-written `generated/flake.lock` against the revs `knixl.lock.kdl` pins for each
/// top-level input (ADR 0014). `None` means the file is missing, which is itself a problem: the
/// generated flake only reproduces with its lock committed beside it.
pub fn flake_lock_problems(
    lock_text: Option<&str>,
    expected: &std::collections::BTreeMap<String, String>,
) -> Vec<String> {
    const RELOCK: &str = "re-lock with `nix flake lock` in generated/, or run `knixl upgrade` \
                          if knixl.lock.kdl is the side that is behind";
    let Some(text) = lock_text else {
        return vec![
            "generated/flake.lock is missing: run `nix flake lock` in generated/ and commit it"
                .into(),
        ];
    };
    let json: serde_json::Value = match serde_json::from_str(text) {
        Ok(v) => v,
        Err(e) => return vec![format!("generated/flake.lock does not parse: {e}")],
    };
    let nodes = &json["nodes"];
    let root = &nodes[json["root"].as_str().unwrap_or("root")];
    let mut problems = Vec::new();
    for (name, want) in expected {
        let locked = root["inputs"][name]
            .as_str()
            .and_then(|key| nodes[key]["locked"]["rev"].as_str());
        match locked {
            None => problems.push(format!(
                "generated/flake.lock has no locked input `{name}`: {RELOCK}"
            )),
            Some(got) if got != want => problems.push(format!(
                "generated/flake.lock pins `{name}` at {got}, knixl.lock.kdl at {want}: {RELOCK}"
            )),
            Some(_) => {}
        }
    }
    problems
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hosts() -> Vec<FlakeHost> {
        vec![
            FlakeHost {
                name: "web".into(),
                baseline_rev: "rev-web".into(),
                module_path: "./hosts/web.nix".into(),
                system: Some("x86_64-linux".into()),
                input_modules: vec![],
                inline_modules: vec![],
            },
            FlakeHost {
                name: "db".into(),
                baseline_rev: "rev-db".into(),
                module_path: "./hosts/db.nix".into(),
                system: Some("aarch64-linux".into()),
                input_modules: vec![],
                inline_modules: vec![],
            },
        ]
    }

    #[test]
    fn deterministic_and_name_ordered() {
        let a = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        let b = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        assert_eq!(a, b, "same input, byte-identical");
        // Order-independent: reversing the input yields the same text (sorted by name).
        let mut rev = hosts();
        rev.reverse();
        assert_eq!(
            render_system_flake(&rev, &[], "25.05", "https://github.com/NixOS/nixpkgs"),
            a
        );
        // db precedes web in the output.
        assert!(
            a.find("\"db\"").unwrap() < a.find("\"web\"").unwrap(),
            "name order: {a}"
        );
    }

    #[test]
    fn emits_per_host_pin_and_state_version() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://example.com/nixpkgs");
        assert!(out.contains("nixosConfigurations"));
        assert!(out.contains("\"web\""));
        assert!(out.contains("rev-web"));
        assert!(out.contains("rev-db"));
        assert!(out.contains("./hosts/web.nix"));
        assert!(out.contains("system.stateVersion = \"25.05\""));
        assert!(out.contains("https://example.com/nixpkgs"));
        assert!(out.contains("builtins.fetchGit"));
        assert!(!out.contains("inputs ="), "no flake inputs");
        // Regression guard: the flake must use eval-config.nix, never lib.nixosSystem (which
        // does not exist on a plain imported nixpkgs set and fails to evaluate).
        assert!(
            out.contains("eval-config.nix"),
            "uses the eval-config constructor: {out}"
        );
        assert!(
            !out.contains("nixosSystem"),
            "must not use lib.nixosSystem: {out}"
        );
    }

    #[test]
    fn escapes_quotes_in_interpolated_values() {
        let hs = vec![FlakeHost {
            name: "web".into(),
            baseline_rev: "rev".into(),
            module_path: "./hosts/web.nix".into(),
            system: None,
            input_modules: vec![],
            inline_modules: vec![],
        }];
        // A url with a quote must not break out of its Nix string literal.
        let out = render_system_flake(&hs, &[], "25.05", "https://x/\"evil");
        assert!(out.contains("https://x/\\\"evil"), "quote escaped: {out}");
    }

    #[test]
    fn emits_installer_config_and_iso_package_output() {
        use crate::project::ImageKind;
        let images = vec![FlakeImage {
            name: "usb".into(),
            baseline_rev: "rev-inst".into(),
            module_path: "./installer/usb.nix".into(),
            system: "x86_64-linux".into(),
            kind: ImageKind::Installer,
        }];
        let out = render_system_flake(&hosts(), &images, "25.05", "https://x/nixpkgs");
        // a let binding the config, referenced by both nixosConfigurations and packages
        assert!(out.contains("image_usb = evalAt \"rev-inst\""));
        assert!(out.contains("./installer/usb.nix"));
        assert!(out.contains("\"usb\" = image_usb;"));
        // the ISO package output, keyed by the installer's system
        assert!(out.contains("packages = {"));
        assert!(out.contains("\"x86_64-linux\" = {"));
        assert!(
            out.contains("\"usb-iso\" = image_usb.config.system.build.isoImage;"),
            "iso output: {out}"
        );
    }

    #[test]
    fn guest_lxc_emits_rootfs_and_metadata_outputs() {
        use crate::project::ImageKind;
        let images = vec![FlakeImage {
            name: "llm".into(),
            baseline_rev: "rev-lxc".into(),
            module_path: "./guest-image/llm.nix".into(),
            system: "x86_64-linux".into(),
            kind: ImageKind::GuestLxc,
        }];
        let out = render_system_flake(&hosts(), &images, "25.05", "https://x/nixpkgs");
        assert!(out.contains("\"llm\" = image_llm;"));
        assert!(
            out.contains("\"llm-lxc\" = image_llm.config.system.build.tarball;"),
            "lxc rootfs output: {out}"
        );
        assert!(
            out.contains("\"llm-lxc-metadata\" = image_llm.config.system.build.metadata;"),
            "lxc metadata output: {out}"
        );
    }

    #[test]
    fn two_images_on_one_system_share_a_single_packages_entry() {
        use crate::project::ImageKind;
        let images = vec![
            FlakeImage {
                name: "usb".into(),
                baseline_rev: "r".into(),
                module_path: "./installer/usb.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::Installer,
            },
            FlakeImage {
                name: "llm".into(),
                baseline_rev: "r".into(),
                module_path: "./guest-image/llm.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::GuestLxc,
            },
        ];
        let out = render_system_flake(&[], &images, "25.05", "https://x/nixpkgs");
        // Exactly one `"x86_64-linux" = {` under packages, not one per image (which would be a
        // duplicate attribute Nix rejects).
        assert_eq!(
            out.matches("\"x86_64-linux\" = {").count(),
            1,
            "one packages.<system> set: {out}"
        );
        assert!(out.contains("\"usb-iso\""));
        assert!(out.contains("\"llm-lxc\""));
    }

    #[test]
    fn no_images_means_no_packages_output() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://x/nixpkgs");
        assert!(!out.contains("packages = {"), "no packages when no images");
    }

    fn inputs() -> Vec<FlakeInputSpec> {
        vec![
            FlakeInputSpec {
                name: "nixpkgs".into(),
                url: pinned_url("github:NixOS/nixpkgs", "rev-np"),
                flake: true,
                follows: vec![],
            },
            FlakeInputSpec {
                name: "disko".into(),
                url: pinned_url("github:nix-community/disko", "rev-disko"),
                flake: true,
                follows: vec![("nixpkgs".into(), "nixpkgs".into())],
            },
        ]
    }

    #[test]
    fn pinned_url_writes_the_rev_into_the_ref() {
        assert_eq!(pinned_url("github:o/r", "abc"), "github:o/r/abc");
        assert_eq!(
            pinned_url("github:o/r?dir=x", "abc"),
            "github:o/r/abc?dir=x"
        );
        assert_eq!(
            pinned_url("git+https://example.com/r", "abc"),
            "git+https://example.com/r?rev=abc"
        );
        assert_eq!(
            pinned_url("git+https://example.com/r?ref=main", "abc"),
            "git+https://example.com/r?ref=main&rev=abc"
        );
    }

    #[test]
    fn input_flake_pins_inputs_and_builds_with_nixos_system() {
        let out = render_input_flake(&inputs(), &hosts(), &[], "25.11", None);
        assert!(out.contains("\"nixpkgs\" = {\n      url = \"github:NixOS/nixpkgs/rev-np\";"));
        assert!(out.contains("url = \"github:nix-community/disko/rev-disko\";"));
        assert!(out.contains("inputs.\"nixpkgs\".follows = \"nixpkgs\";"));
        assert!(out.contains("outputs = { nixpkgs, ... }@inputs:"));
        assert!(out
            .contains("\"web\" = nixpkgs.lib.nixosSystem {\n          system = \"x86_64-linux\";"));
        assert!(out
            .contains("\"db\" = nixpkgs.lib.nixosSystem {\n          system = \"aarch64-linux\";"));
        assert!(!out.contains("fetchGit"), "{out}");
        assert!(!out.contains("formatter"), "{out}");
        assert!(
            out.find("\"disko\" = {").unwrap() < out.find("\"nixpkgs\" = {").unwrap(),
            "inputs in name order: {out}"
        );
        let mut reversed = inputs();
        reversed.reverse();
        assert_eq!(
            render_input_flake(&reversed, &hosts(), &[], "25.11", None),
            out
        );
    }

    #[test]
    fn input_flake_lists_input_modules_ahead_of_the_host_module() {
        let mut hs = hosts();
        hs[0].input_modules = vec![
            "inputs.\"disko\".nixosModules.\"disko\"".into(),
            "inputs.\"sops-nix\".nixosModules.\"sops\"".into(),
        ];
        let out = render_input_flake(&inputs(), &hs, &[], "25.11", None);
        assert!(
            out.contains("modules = [\n            inputs.\"disko\".nixosModules.\"disko\"\n            inputs.\"sops-nix\".nixosModules.\"sops\"\n            ./hosts/web.nix\n"),
            "{out}"
        );
        assert!(
            out.contains("modules = [\n            ./hosts/db.nix\n"),
            "{out}"
        );
    }

    #[test]
    fn input_flake_emits_flake_false_and_a_formatter_per_host_system() {
        let mut ins = inputs();
        ins.push(FlakeInputSpec {
            name: "blobs".into(),
            url: "github:o/blobs/rev-b".into(),
            flake: false,
            follows: vec![],
        });
        let out = render_input_flake(&ins, &hosts(), &[], "25.11", Some("nixfmt-rfc-style"));
        assert!(out.contains("url = \"github:o/blobs/rev-b\";\n      flake = false;"));
        assert!(out.contains(
            "\"aarch64-linux\" = nixpkgs.legacyPackages.\"aarch64-linux\".\"nixfmt-rfc-style\";"
        ));
        assert!(out.contains(
            "\"x86_64-linux\" = nixpkgs.legacyPackages.\"x86_64-linux\".\"nixfmt-rfc-style\";"
        ));
    }

    #[test]
    fn input_flake_passes_system_for_installers_but_not_guest_images() {
        use crate::project::ImageKind;
        let images = vec![
            FlakeImage {
                name: "usb".into(),
                baseline_rev: "rev-np".into(),
                module_path: "./installer/usb.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::Installer,
            },
            FlakeImage {
                name: "llm".into(),
                baseline_rev: "rev-np".into(),
                module_path: "./guest-image/llm.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::GuestLxc,
            },
        ];
        let out = render_input_flake(&inputs(), &[], &images, "25.11", None);
        assert!(out
            .contains("image_usb = nixpkgs.lib.nixosSystem {\n        system = \"x86_64-linux\";"));
        assert!(out.contains("image_llm = nixpkgs.lib.nixosSystem {\n        modules = ["));
        assert!(out.contains("\"llm-lxc\" = image_llm.config.system.build.tarball;"));
        assert!(out.contains("\"usb-iso\" = image_usb.config.system.build.isoImage;"));
    }

    #[test]
    fn flake_lock_problems_compare_each_top_level_input() {
        let expected = std::collections::BTreeMap::from([
            ("nixpkgs".to_string(), "aaa".to_string()),
            ("disko".to_string(), "bbb".to_string()),
        ]);
        // `nixpkgs_2` mirrors how nix names a node when a transitive input shares the name.
        let lock = r#"{
          "nodes": {
            "disko": { "locked": { "rev": "bbb" } },
            "nixpkgs_2": { "locked": { "rev": "aaa" } },
            "root": { "inputs": { "disko": "disko", "nixpkgs": "nixpkgs_2" } }
          },
          "root": "root",
          "version": 7
        }"#;
        assert!(flake_lock_problems(Some(lock), &expected).is_empty());

        let stale = lock.replace("\"rev\": \"aaa\"", "\"rev\": \"zzz\"");
        let problems = flake_lock_problems(Some(&stale), &expected);
        assert_eq!(problems.len(), 1, "{problems:?}");
        assert!(problems[0].contains("pins `nixpkgs` at zzz, knixl.lock.kdl at aaa"));

        let missing = flake_lock_problems(None, &expected);
        assert!(missing[0].contains("is missing"), "{missing:?}");

        let no_disko = lock.replace("\"disko\": \"disko\", ", "");
        assert!(
            flake_lock_problems(Some(&no_disko), &expected)[0].contains("no locked input `disko`")
        );
    }
}
