//! Emit the opt-in system-assembly flake (ADR 0009): nixosConfigurations.<host>, each host
//! built against its own baseline nixpkgs rev, pinned by fetchGit (a full rev is a pure pin).

#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeHost {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
}

/// An image target (ADR 0012, 0013): an installer ISO or an lxc image. `system` is the platform
/// double keying its `packages.<system>` output; `baseline_rev` pins nixpkgs like a host; `kind`
/// selects the flake output shape.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct FlakeImage {
    pub name: String,
    pub baseline_rev: String,
    pub module_path: String,
    pub system: String,
    pub kind: crate::project::ImageKind,
}

impl FlakeImage {
    /// The `packages.<system>` outputs this image contributes, as `(output-name, expression)`
    /// where the expression reads a build product off the image's evaluated config (`binding`).
    fn outputs(&self, binding: &str) -> Vec<(String, String)> {
        match self.kind {
            crate::project::ImageKind::Installer => vec![(
                format!("{}-iso", self.name),
                format!("{binding}.config.system.build.isoImage"),
            )],
            // incus image import takes both a rootfs and a metadata tarball, so both are exposed.
            crate::project::ImageKind::GuestLxc => vec![
                (
                    format!("{}-lxc", self.name),
                    format!("{binding}.config.system.build.tarball"),
                ),
                (
                    format!("{}-lxc-metadata", self.name),
                    format!("{binding}.config.system.build.metadata"),
                ),
            ],
        }
    }
}

/// A Nix identifier derived from an image name for a `let` binding (names are simple in practice,
/// but hyphens and other non-ident chars are mapped to `_` defensively).
fn let_ident(name: &str) -> String {
    let mut out = String::from("image_");
    for c in name.chars() {
        out.push(if c.is_ascii_alphanumeric() { c } else { '_' });
    }
    out
}

/// Escape a value spliced into a Nix double-quoted string literal: backslash, double-quote,
/// and the antiquotation opener `${`.
fn esc(v: &str) -> String {
    v.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace("${", "\\${")
}

/// Render the system flake. Hosts are emitted in `name` order so the output is a pure function
/// of the input set (sorted here defensively, independent of caller order). The text is
/// unformatted Nix; the caller runs it through the pinned formatter before hashing.
///
/// Each host is built with `nixos/lib/eval-config.nix` from its baseline nixpkgs: that is the
/// self-contained system constructor. `lib.nixosSystem` is a flake-only lib extension and is
/// NOT present on a plain `import <nixpkgs> {}` set, so it cannot be used here. `fetchGit` with
/// a full rev is a pure pin; `shallow = true` matches the package-pin emit idiom.
pub fn render_system_flake(
    hosts: &[FlakeHost],
    images: &[FlakeImage],
    state_version: &str,
    nixpkgs_url: &str,
) -> String {
    let mut sorted: Vec<&FlakeHost> = hosts.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    let mut inst: Vec<&FlakeImage> = images.iter().collect();
    inst.sort_by(|a, b| a.name.cmp(&b.name));

    let mut s = String::new();
    s.push_str("# Generated by knixl. Do NOT edit; regenerate with `knixl generate`.\n");
    s.push_str("{\n");
    s.push_str("  description = \"knixl-generated system\";\n");
    s.push_str("  outputs = { ... }:\n");
    s.push_str("    let\n");
    s.push_str(&format!(
        "      evalAt = rev: import \"${{builtins.fetchGit {{ url = \"{}\"; rev = rev; shallow = true; }}}}/nixos/lib/eval-config.nix\";\n",
        esc(nixpkgs_url)
    ));
    // One `let` binding per image target, so both nixosConfigurations and packages can name the
    // same evaluated configuration (ADR 0012, 0013).
    for i in &inst {
        s.push_str(&format!(
            "      {} = evalAt \"{}\" {{\n",
            let_ident(&i.name),
            esc(&i.baseline_rev)
        ));
        s.push_str("        modules = [\n");
        s.push_str(&format!("          {}\n", i.module_path));
        s.push_str(&format!(
            "          {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("        ];\n");
        s.push_str("      };\n");
    }
    s.push_str("    in\n");
    s.push_str("    {\n");
    s.push_str("      nixosConfigurations = {\n");
    for h in sorted {
        s.push_str(&format!(
            "        \"{}\" = evalAt \"{}\" {{\n",
            esc(&h.name),
            esc(&h.baseline_rev)
        ));
        s.push_str("          modules = [\n");
        s.push_str(&format!("            {}\n", h.module_path));
        s.push_str(&format!(
            "            {{ system.stateVersion = \"{}\"; }}\n",
            esc(state_version)
        ));
        s.push_str("          ];\n");
        s.push_str("        };\n");
    }
    for i in &inst {
        s.push_str(&format!(
            "        \"{}\" = {};\n",
            esc(&i.name),
            let_ident(&i.name)
        ));
    }
    s.push_str("      };\n");
    // Image build outputs, grouped by target system (so two images on the same system share one
    // `packages.<system>` set rather than emitting a duplicate key).
    if !inst.is_empty() {
        let mut by_system: std::collections::BTreeMap<&str, Vec<(String, String)>> =
            std::collections::BTreeMap::new();
        for i in &inst {
            by_system
                .entry(i.system.as_str())
                .or_default()
                .extend(i.outputs(&let_ident(&i.name)));
        }
        s.push_str("      packages = {\n");
        for (system, mut outs) in by_system {
            outs.sort_by(|a, b| a.0.cmp(&b.0));
            s.push_str(&format!("        \"{}\" = {{\n", esc(system)));
            for (name, expr) in outs {
                s.push_str(&format!("          \"{}\" = {};\n", esc(&name), expr));
            }
            s.push_str("        };\n");
        }
        s.push_str("      };\n");
    }
    s.push_str("    };\n");
    s.push_str("}\n");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hosts() -> Vec<FlakeHost> {
        vec![
            FlakeHost {
                name: "web".into(),
                baseline_rev: "rev-web".into(),
                module_path: "./hosts/web.nix".into(),
            },
            FlakeHost {
                name: "db".into(),
                baseline_rev: "rev-db".into(),
                module_path: "./hosts/db.nix".into(),
            },
        ]
    }

    #[test]
    fn deterministic_and_name_ordered() {
        let a = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        let b = render_system_flake(&hosts(), &[], "25.05", "https://github.com/NixOS/nixpkgs");
        assert_eq!(a, b, "same input, byte-identical");
        // Order-independent: reversing the input yields the same text (sorted by name).
        let mut rev = hosts();
        rev.reverse();
        assert_eq!(
            render_system_flake(&rev, &[], "25.05", "https://github.com/NixOS/nixpkgs"),
            a
        );
        // db precedes web in the output.
        assert!(
            a.find("\"db\"").unwrap() < a.find("\"web\"").unwrap(),
            "name order: {a}"
        );
    }

    #[test]
    fn emits_per_host_pin_and_state_version() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://example.com/nixpkgs");
        assert!(out.contains("nixosConfigurations"));
        assert!(out.contains("\"web\""));
        assert!(out.contains("rev-web"));
        assert!(out.contains("rev-db"));
        assert!(out.contains("./hosts/web.nix"));
        assert!(out.contains("system.stateVersion = \"25.05\""));
        assert!(out.contains("https://example.com/nixpkgs"));
        assert!(out.contains("builtins.fetchGit"));
        assert!(!out.contains("inputs ="), "no flake inputs");
        // Regression guard: the flake must use eval-config.nix, never lib.nixosSystem (which
        // does not exist on a plain imported nixpkgs set and fails to evaluate).
        assert!(
            out.contains("eval-config.nix"),
            "uses the eval-config constructor: {out}"
        );
        assert!(
            !out.contains("nixosSystem"),
            "must not use lib.nixosSystem: {out}"
        );
    }

    #[test]
    fn escapes_quotes_in_interpolated_values() {
        let hs = vec![FlakeHost {
            name: "web".into(),
            baseline_rev: "rev".into(),
            module_path: "./hosts/web.nix".into(),
        }];
        // A url with a quote must not break out of its Nix string literal.
        let out = render_system_flake(&hs, &[], "25.05", "https://x/\"evil");
        assert!(out.contains("https://x/\\\"evil"), "quote escaped: {out}");
    }

    #[test]
    fn emits_installer_config_and_iso_package_output() {
        use crate::project::ImageKind;
        let images = vec![FlakeImage {
            name: "usb".into(),
            baseline_rev: "rev-inst".into(),
            module_path: "./installer/usb.nix".into(),
            system: "x86_64-linux".into(),
            kind: ImageKind::Installer,
        }];
        let out = render_system_flake(&hosts(), &images, "25.05", "https://x/nixpkgs");
        // a let binding the config, referenced by both nixosConfigurations and packages
        assert!(out.contains("image_usb = evalAt \"rev-inst\""));
        assert!(out.contains("./installer/usb.nix"));
        assert!(out.contains("\"usb\" = image_usb;"));
        // the ISO package output, keyed by the installer's system
        assert!(out.contains("packages = {"));
        assert!(out.contains("\"x86_64-linux\" = {"));
        assert!(
            out.contains("\"usb-iso\" = image_usb.config.system.build.isoImage;"),
            "iso output: {out}"
        );
    }

    #[test]
    fn guest_lxc_emits_rootfs_and_metadata_outputs() {
        use crate::project::ImageKind;
        let images = vec![FlakeImage {
            name: "llm".into(),
            baseline_rev: "rev-lxc".into(),
            module_path: "./guest-image/llm.nix".into(),
            system: "x86_64-linux".into(),
            kind: ImageKind::GuestLxc,
        }];
        let out = render_system_flake(&hosts(), &images, "25.05", "https://x/nixpkgs");
        assert!(out.contains("\"llm\" = image_llm;"));
        assert!(
            out.contains("\"llm-lxc\" = image_llm.config.system.build.tarball;"),
            "lxc rootfs output: {out}"
        );
        assert!(
            out.contains("\"llm-lxc-metadata\" = image_llm.config.system.build.metadata;"),
            "lxc metadata output: {out}"
        );
    }

    #[test]
    fn two_images_on_one_system_share_a_single_packages_entry() {
        use crate::project::ImageKind;
        let images = vec![
            FlakeImage {
                name: "usb".into(),
                baseline_rev: "r".into(),
                module_path: "./installer/usb.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::Installer,
            },
            FlakeImage {
                name: "llm".into(),
                baseline_rev: "r".into(),
                module_path: "./guest-image/llm.nix".into(),
                system: "x86_64-linux".into(),
                kind: ImageKind::GuestLxc,
            },
        ];
        let out = render_system_flake(&[], &images, "25.05", "https://x/nixpkgs");
        // Exactly one `"x86_64-linux" = {` under packages, not one per image (which would be a
        // duplicate attribute Nix rejects).
        assert_eq!(
            out.matches("\"x86_64-linux\" = {").count(),
            1,
            "one packages.<system> set: {out}"
        );
        assert!(out.contains("\"usb-iso\""));
        assert!(out.contains("\"llm-lxc\""));
    }

    #[test]
    fn no_images_means_no_packages_output() {
        let out = render_system_flake(&hosts(), &[], "25.05", "https://x/nixpkgs");
        assert!(!out.contains("packages = {"), "no packages when no images");
    }
}
